server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/endpointops
    username: endpointops
    password: endpointops
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
